// Havok translation unit hkConvexVerticesShape.o (main.dol 0x802D1588-0x802D256C).
// Not yet decompiled. Functions in address order (method names from the Havok TU map; classes still to be identified):
//   0x802D1588    32  finishLoadedObjecthkConvexVerticesShape   [map: hkConvexVerticesShape__finishLoadedObjecthkConvexVerticesShape]
//   0x802D15A8    20  cleanupLoadedObjecthkConvexVerticesShape   [map: hkConvexVerticesShape__cleanupLoadedObjecthkConvexVerticesShape]
//   0x802D15BC   196  __dt   [map: hkConvexVerticesShape____dt]
//   0x802D1680    60  getVtablehkConvexVerticesShape   [map: hkConvexVerticesShape__getVtablehkConvexVerticesShape]
//   0x802D16BC     8  getType   [map: hkConvexVerticesShape__getType]
//   0x802D16C4    48  getFirstVertex   [map: hkConvexVerticesShape__getFirstVertex]
//   0x802D16F4    20  getCollisionSpheresInfo   [map: hkConvexVerticesShape__getCollisionSpheresInfo]
//   0x802D1708   452  getCollisionSpheres   [map: hkConvexVerticesShape__getCollisionSpheres]
//   0x802D18CC  1004  getAabb   [map: hkConvexVerticesShape__getAabb]
//   0x802D1CB8   800  getSupportingVertex   [map: hkConvexVerticesShape__getSupportingVertex]
//   0x802D1FD8   324  convertVertexIdsToVertices   [map: hkConvexVerticesShape__convertVertexIdsToVertices]
//   0x802D211C   776  castRay   [map: hkConvexVerticesShape__castRay]
//   0x802D2424   244  calcStatistics   [map: hkConvexVerticesShape__calcStatistics]
//   0x802D2518    84  __sinit_\hkConvexVerticesShape_cpp   [map: hkConvexVerticesShapecpp____sinit_]
