// Havok translation unit hkKeyframedRigidMotion.o (main.dol 0x802E5564-0x802E5A28).
// Not yet decompiled. Functions in address order (method names from the Havok TU map; classes still to be identified):
//   0x802E5564    32  finishLoadedObjecthkKeyframedRigidMotion   [map: hkKeyframedRigidMotion__finishLoadedObjecthkKeyframedRigidMotion]
//   0x802E5584    20  cleanupLoadedObjecthkKeyframedRigidMotion   [map: hkKeyframedRigidMotion__cleanupLoadedObjecthkKeyframedRigidMotion]
//   0x802E5598    60  getVtablehkKeyframedRigidMotion   [map: hkKeyframedRigidMotion__getVtablehkKeyframedRigidMotion]
//   0x802E55D4    32  finishLoadedObjecthkMaxSizeMotion   [map: hkKeyframedRigidMotion__finishLoadedObjecthkMaxSizeMotion]
//   0x802E55F4    20  cleanupLoadedObjecthkMaxSizeMotion   [map: hkKeyframedRigidMotion__cleanupLoadedObjecthkMaxSizeMotion]
//   0x802E5608    60  getVtablehkMaxSizeMotion   [map: hkKeyframedRigidMotion__getVtablehkMaxSizeMotion]
//   0x802E5644   100  __ct   [map: hkKeyframedRigidMotion____ct]
//   0x802E56A8   176  __dt   [map: hkKeyframedRigidMotion____dt]
//   0x802E5758     4  setMass   [map: hkKeyframedRigidMotion__setMass]
//   0x802E575C     4  setMassInv   [map: hkKeyframedRigidMotion__setMassInv]
//   0x802E5760    96  getInertiaLocal   [map: hkKeyframedRigidMotion__getInertiaLocal]
//   0x802E57C0    96  getInertiaWorld   [map: hkKeyframedRigidMotion__getInertiaWorld]
//   0x802E5820     4  setInertiaLocal   [map: hkKeyframedRigidMotion__setInertiaLocal]
//   0x802E5824     4  setInertiaInvLocal   [map: hkKeyframedRigidMotion__setInertiaInvLocal]
//   0x802E5828    96  getInertiaInvLocal   [map: hkKeyframedRigidMotion__getInertiaInvLocal]
//   0x802E5888    96  getInertiaInvWorld   [map: hkKeyframedRigidMotion__getInertiaInvWorld]
//   0x802E58E8     4  applyLinearImpulse   [map: hkKeyframedRigidMotion__applyLinearImpulse]
//   0x802E58EC     4  applyPointImpulse   [map: hkKeyframedRigidMotion__applyPointImpulse]
//   0x802E58F0     4  applyAngularImpulse   [map: hkKeyframedRigidMotion__applyAngularImpulse]
//   0x802E58F4     4  applyForce   [map: hkKeyframedRigidMotion__applyForce]
//   0x802E58F8     4  applyForce   [map: hkKeyframedRigidMotion__applyForce1]
//   0x802E58FC     4  applyTorque   [map: hkKeyframedRigidMotion__applyTorque]
//   0x802E5900     4  setStepPosition   [map: hkKeyframedRigidMotion__setStepPosition]
//   0x802E5904   156  setStoredMotion   [map: hkKeyframedRigidMotion__setStoredMotion]
//   0x802E59A0   136  __sinit_\hkKeyframedRigidMotion_cpp   [map: hkKeyframedRigidMotioncpp____sinit_]
