// Havok translation unit hkPoweredChainSolverUtil.o (main.dol 0x80290594-0x80293CBC).
// Not yet decompiled. Functions in address order (method names from the Havok TU map; classes still to be identified):
//   0x80290594  1016  hkPoweredChainBuildJacobian   [map: hkPoweredChainSolverUtil__hkPoweredChainBuildJacobian]
//   0x8029098C   308  hkPoweredChain_BuildConstraintMatrixAndLuDecomposition   [map: hkPoweredChainSolverUtil__hkPoweredChain_BuildConstraintMatrixAndLuDecomposition]
//   0x80290AC0     4  __ct   [map: hkMatrix6____ct]
//   0x80290AC4   288  setZero   [map: hkMatrix6__setZero]
//   0x80290BE4  1676  hkPoweredChain_ComputeConstraintMatrix_DiagonalAtRow   [map: hkPoweredChainSolverUtil__hkPoweredChain_ComputeConstraintMatrix_DiagonalAtRow]
//   0x80291270    20  __cl   [map: hkMatrix3____cl]
//   0x80291284   824  hkPoweredChain_ComputeConstraintMatrix_NextOffDiagonalAtR   [map: hkPoweredChainSolverUtil__hkPoweredChain_ComputeConstraintMatrix_NextOffDiagonalAtRow]
//   0x802915BC     8  __ct   [map: hkBool____ct]
//   0x802915C4   888  hkPoweredChain_UpdateLuDecomposition   [map: hkPoweredChainSolverUtil__hkPoweredChain_UpdateLuDecomposition]
//   0x8029193C   820  __as   [map: hkMatrix6____as]
//   0x80291C70   360  hkPoweredChain_ComputeConstraintMatrixLuDecomposition_For   [map: hkPoweredChainSolverUtil__hkPoweredChain_ComputeConstraintMatrixLuDecomposition_ForOneRow]
//   0x80291DD8    16  max2<f>   [map: hkMath__max2_f_]
//   0x80291DE8   820  __ct   [map: hkMatrix6____ct1]
//   0x8029211C   148  hkPoweredChain_DisableMotorInMatrixRow_ThisConstraint   [map: hkPoweredChainSolverUtil__hkPoweredChain_DisableMotorInMatrixRow_ThisConstraint]
//   0x802921B0   172  hkPoweredChain_DisableMotorInMatrixRow_NextConstraint   [map: hkPoweredChainSolverUtil__hkPoweredChain_DisableMotorInMatrixRow_NextConstraint]
//   0x8029225C  2248  hkPoweredChain_CalculateVelocities   [map: hkPoweredChainSolverUtil__hkPoweredChain_CalculateVelocities]
//   0x80292B24    84  hkPoweredChain_OverwriteVelocityWithExplicitImpulse   [map: hkPoweredChainSolverUtil__hkPoweredChain_OverwriteVelocityWithExplicitImpulse]
//   0x80292B78   964  hkPoweredChain_RestoreVelocityValue   [map: hkPoweredChainSolverUtil__hkPoweredChain_RestoreVelocityValue]
//   0x80292F3C   332  hkPoweredChain_SolveConstraintMatrix_ComputeVectorG   [map: hkPoweredChainSolverUtil__hkPoweredChain_SolveConstraintMatrix_ComputeVectorG]
//   0x80293088   636  hkPoweredChain_ScanAndDisableMotors   [map: hkPoweredChainSolverUtil__hkPoweredChain_ScanAndDisableMotors]
//   0x80293304  2488  hkPoweredChain_ScanAndEnableMotors   [map: hkPoweredChainSolverUtil__hkPoweredChain_ScanAndEnableMotors]
