// Havok translation unit hkSimulationIsland.o (main.dol 0x802E9BFC-0x802EA88C).
// Not yet decompiled. Functions in address order (method names from the Havok TU map; classes still to be identified):
//   0x802E9BFC   252  __ct   [map: hkSimulationIsland____ct]
//   0x802E9CF8   260  __dt   [map: hkSimulationIsland____dt]
//   0x802E9DFC   120  internalAddEntity   [map: hkSimulationIsland__internalAddEntity]
//   0x802E9E74   104  internalRemoveEntity   [map: hkSimulationIsland__internalRemoveEntity]
//   0x802E9EDC   796  calcStatistics   [map: hkSimulationIsland__calcStatistics]
//   0x802EA1F8   112  addAction   [map: hkSimulationIsland__addAction]
//   0x802EA268   104  removeAction   [map: hkSimulationIsland__removeAction]
//   0x802EA2D0   864  isFullyConnected   [map: hkSimulationIsland__isFullyConnected]
//   0x802EA630   476  shouldDeactivate   [map: hkSimulationIsland__shouldDeactivate]
//   0x802EA80C    12  addConstraintToCriticalLockedIsland   [map: hkSimulationIsland__addConstraintToCriticalLockedIsland]
//   0x802EA818    12  removeConstraintFromCriticalLockedIsland   [map: hkSimulationIsland__removeConstraintFromCriticalLockedIsland]
//   0x802EA824    96  mergeConstraintInfo   [map: hkSimulationIsland__mergeConstraintInfo]
//   0x802EA884     4  markForWrite   [map: hkSimulationIsland__markForWrite]
//   0x802EA888     4  checkAccessRw   [map: hkConstraintOwner__checkAccessRw]
