// Havok translation unit hkSphereMotion.o (main.dol 0x802E5AE0-0x802E60EC).
// Not yet decompiled. Functions in address order (method names from the Havok TU map; classes still to be identified):
//   0x802E5AE0    32  finishLoadedObjecthkSphereMotion   [map: hkSphereMotion__finishLoadedObjecthkSphereMotion]
//   0x802E5B00    20  cleanupLoadedObjecthkSphereMotion   [map: hkSphereMotion__cleanupLoadedObjecthkSphereMotion]
//   0x802E5B14    60  getVtablehkSphereMotion   [map: hkSphereMotion__getVtablehkSphereMotion]
//   0x802E5B50   108  getInertiaLocal   [map: hkSphereMotion__getInertiaLocal]
//   0x802E5BBC   108  getInertiaWorld   [map: hkSphereMotion__getInertiaWorld]
//   0x802E5C28    80  setInertiaLocal   [map: hkSphereMotion__setInertiaLocal]
//   0x802E5C78    60  setInertiaInvLocal   [map: hkSphereMotion__setInertiaInvLocal]
//   0x802E5CB4   100  getInertiaInvLocal   [map: hkSphereMotion__getInertiaInvLocal]
//   0x802E5D18   100  getInertiaInvWorld   [map: hkSphereMotion__getInertiaInvWorld]
//   0x802E5D7C   364  applyPointImpulse   [map: hkSphereMotion__applyPointImpulse]
//   0x802E5EE8    84  applyAngularImpulse   [map: hkSphereMotion__applyAngularImpulse]
//   0x802E5F3C   128  applyForce   [map: hkSphereMotion__applyForce]
//   0x802E5FBC   112  applyForce   [map: hkSphereMotion__applyForce1]
//   0x802E602C   112  applyTorque   [map: hkSphereMotion__applyTorque]
//   0x802E609C    80  __sinit_\hkSphereMotion_cpp   [map: hkSphereMotioncpp____sinit_]
